---
title: "Community Detection"
description: |
  Detecting Communities in out Football Transfer Network
author:
  - name: Isha Mahajan, Ankit Kumar
    affiliation: UMass Amherst
date: 2022-05-10
output:
  distill::distill_article:
    self_contained: false
---

## Week 7: Community Detection 

# Fast and Greedy Community Detection

```{r include=FALSE}
library(igraph)
library(tidyverse)
library(corrr)
library(intergraph)
library(statnet)
library(network)
library(sna)
library(ggplot2)
```


```{r include=FALSE}
transfers <- read_csv("/Users/isha/Desktop/GitHub/transfernetworks.csv")
head(transfers)
#select relevant data for edgelist format
data <- transfers %>% 
  select(club_from, club_to, name,fee) %>% 
  filter(fee != "free transfer") %>% 
  filter(fee != "loan transfer") %>% 
  filter (fee != 0)
data$fee <- as.numeric(data$fee) 
data <- data %>% 
filter(fee != is.na(fee))
any(is.na(data$fee))
```

## Create Edgelist

```{r include=FALSE}
#convert data into matrix format
data.mat <- as.matrix(data)
#create igraph object from data
ig <- graph_from_data_frame(data.mat, directed = TRUE)
# add edge attribute weight i.e transfer fee
ig <- set_edge_attr(ig, "weight", value = na.omit(data$fee))
# add edge attribute season of transfer
#ig<-  set_edge_attr(ig, "season", value = na.omit(data$season))
# add node attribute i.e league the club belongs to
#set_vertex_attr(ig,"league" ,value = node_attr)
#delete edge attribute that was automatically being created in addition to weight
ig <- delete_edge_attr(ig, "fee")
#check summary of the igraph object
summary(ig)
transfer.nodes<-data.frame(name=V(ig)$name, degree=igraph::degree(ig))
#create indegree and outdegree column
transfer.nodes<-transfer.nodes %>%
           mutate(indegree=igraph::degree(ig, mode="in", loops=FALSE),
           outdegree=igraph::degree(ig, mode="out", loops=FALSE))
```


```{r results='hide'}
ig.undirected <- as.undirected(ig)
#Run clustering algorithm: fast_greedy
transfer.fg<-cluster_fast_greedy(ig.undirected)
#Inspect clustering object
names(transfer.fg)
```


```{r results='hide'}
transfer.fg
```

```{r results='hide'}
#retrieve list of nodes in communities
igraph::groups(transfer.fg)
```

## Adding Community Membership to Node Info

```{r results='hide'}
#Inspect community membership vector
transfer.fg$membership
#Compare to vertex names vector
transfer.fg$names
#Membership function
membership(transfer.fg)
#Check order of vertex names
V(ig)$name
```



```{r results='hide'}
#add community membership as a node attribute
transfer.nodes$transfer.fg<-transfer.fg$membership
#summarize node statistics by community
transfer.nodes%>%
  select(-name)%>% group_by(transfer.fg)%>%
  mutate(n=n())%>%
  summarise_all(mean, na.rm=TRUE)%>%
  as.matrix()%>%
  print(digits=2)
```


```{r}
nodes.by.gp<-function(network.nodes, groupvar){
  network.nodes%>%
  select(-name)%>%
  group_by_(groupvar) %>%
  mutate(n=n())%>%
  summarise_all(mean, na.rm=TRUE)%>%
  as.matrix()%>%
  print(digits=2)
}
```

```{r}
plot(transfer.fg,ig)
```


## Walktrap Community Detection


```{r}
#Run clustering algorithm: walktrap
transfer.wt<-walktrap.community(ig)
#Inspect community membership
#igraph::groups(transfer.wt)
```


```{r results = 'hide'}
#Run & inspect clustering algorithm: 10, 20, 100 steps
igraph::groups(walktrap.community(ig, steps=10))
#Run & inspect clustering algorithm: 10 steps
igraph::groups(walktrap.community(ig, steps=20))
```

```{r}
#Run & inspect clustering algorithm: 10 steps
#igraph::groups(walktrap.community(ig, steps=100))
```


```{r}
#inspect density of between/within community ties
#print(blockmodel(matrix,transfer.wt$membership)$block.model, digits=2)
```

```{r results = 'hide'}
#add community membership as a vertex attribute
transfer.nodes$transfer.wt<-transfer.wt$membership
#summarize node statistics by community
nodes.by.gp(transfer.nodes,"transfer.wt")
```

```{r}
#plot network with community coloring
plot(transfer.wt,ig)
```

## Compare Community Partitions 

```{r}
#compare community partition modularity scores
modularity(transfer.fg)
```

```{r}
modularity(transfer.wt)
```


```{r}
#collect modularity scores to compare
mods<-c(fastgreedy=modularity(transfer.fg), walktrap=modularity(transfer.wt))
mods
```


```{r}
compare.algs<-function(alg.a,alg.b,compare.meth=c("vi", "nmi", "split.join", "rand", "adjusted.rand")){
  #create list of community objects and methods
  comm.compare<-expand.grid(alg.a=alg.a, alg.b=alg.b, meth=compare.meth, result=NA, stringsAsFactors = FALSE)
  #compare community partitions using a loop
for(i in 1:nrow(comm.compare)){
  comm1<-get(comm.compare$alg.a[i])
  comm2<-get(comm.compare$alg.b[i])
  method<-comm.compare$meth[i]
  comm.compare$result[i]<-compare(comm1, comm2, method)
}
  return(comm.compare)
}
```


```{r}
#compare community partitions
compare.algs(alg.a=c("transfer.fg"),alg.b="transfer.wt")
```


## Leading Label Propogation

```{r results= 'hide'}
#Run clustering algorithm: leading label
transfer.lab<-label.propagation.community(ig)
#Inspect community membership
igraph::groups(transfer.lab)
```

```{r results= 'hide'}
#add community membership as a vertex attribute
transfer.nodes$transfer.lab<-transfer.lab$membership
#summarize node statistics by community
nodes.by.gp(transfer.nodes,"transfer.lab")
```

```{r}
#plot network with community coloring
plot(transfer.lab,ig)
```

```{r}
#compare community partitions
compare.algs(alg.a=c("transfer.fg","transfer.wt"),alg.b="transfer.lab")
```

## Edge Betweeness Community 


```{r results= 'hide'}
#Run clustering algorithm: edge betweenness
transfer.edge<-label.propagation.community(ig)
#Inspect community membership
igraph::groups(transfer.edge)
```

```{r results= 'hide'}
#add community membership as a vertex attribute
transfer.nodes$transfer.edge<-transfer.edge$membership
#summarize node statistics by community
nodes.by.gp(transfer.nodes,"transfer.edge")
```

```{r}
plot(transfer.edge,ig)
```

```{r}
#collect modularity scores to compare
mods<-c(mods, edge=modularity(transfer.edge))
mods
```

```{r}
#compare community partitions
compare.algs(alg.a=c("transfer.fg","transfer.wt", "transfer.lab"), alg.b="transfer.edge")
```


#Eigenvector Community Detection

.
```{r results = 'hide'}
#Run clustering algorithm: leading eigenvector
transfer.eigen<-leading.eigenvector.community(ig)
#Inspect community membership
igraph::groups(transfer.eigen)
```

```{r}
#inspect density of between/within community ties
#print(blockmodel(matrix,transfer.eigen$membership)$block.model, digits=2)
```


```{r}
#add community membership as a vertex attribute
transfer.nodes$transfer.eigen<-transfer.eigen$membership
#summarize node statistics by community
nodes.by.gp(transfer.nodes,"transfer.eigen")
```

```{r}
#plot network with community coloring
plot(transfer.eigen,ig)
```

```{r}
#collect modularity scores to compare
mods<-c(mods, eigen=modularity(transfer.eigen))
mods
```

```{r}
#compare community partitions
compare.algs(alg.a=c("transfer.fg","transfer.wt", "transfer.lab", "transfer.edge"), alg.b="transfer.eigen")
```





